services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_TAG: idealitsol/drone-helm-s3-sops:$CI_COMMIT_TAG

before_script:
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
