kind: pipeline
name: default

steps:
  - name: docker
    pull: always
    image: plugins/docker:18
    settings:
      repo: idealitsol/drone-helm-s3-sops
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request
