kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: idealitsol/drone-helm-s3-sops
      tags: latest
      secrets: [docker_username, docker_password]
