kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: idealitsol/drone-helm-s3-sops
      auto_tag: true
      tags:
        - latest
        - "1.0.1"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
    event:
      - push
      - tag
