kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      repo: idealitsol/drone-helm-s3-sops
      tags: latest
